-   id: prepend-branch-name
    name: prepend each commit message with the branch name
    description: Ensures that all commits on a feature branch can be traced, useful if using rebase merge strategy
    entry: prepend-branch-name/prepend-branch-name.sh
    language: script
    stages: [commit-msg]
-   id: yarn-system-husky-commit
    name: Invoke husky
    description: Wrapper around the call to husky to allow husky pre-commit hooks to be run
    entry: yarn-system-husky/run-husky-commit.sh
    language: script
    verbose: true
    require_serial: true
    stages: [commit]
-   id: yarn-system-husky-commit-msg
    name: Invoke husky
    description: Wrapper around the call to husky to allow husky pre-commit-msg hooks to be run
    entry: yarn-system-husky/run-husky-commit-msg.sh
    language: script
    verbose: true
    require_serial: true
    stages: [commit-msg]
