-   id: prepend-branch-name
    name: prepend each commit message with the branch name
    description: Ensures that all commits on a feature branch can be traced, useful if using rebase merge strategy
    entry: prepend-branch-name/prepend-branch-name.sh
    language: script
    stages: [commit-msg]
-   id: run-husky
    name: Invoke husky
    description: Wrapper around the call to husky to allow husky commit hooks to be run
    entry: run-husky/run-husky.sh
    language: script
    stages: [pre-commit]
